# 1. Menyertakan prefix dan suffix pada seluruh kolom `DataFrame`

## Import modules

In [4]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.2.2
1.26.4

## Persiapan `DataFrame`

In [7]:
n_rows = 5
n_cols = 5
cols = list("ABCDE")

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), columns=cols)
df

   A  B  C  D  E
0  2  9  1  1  7
1  2  8  9  7  2
2  5  3  6  9  6
3  1  9  6  1  9
4  8  6  5  7  2

## Menyertakan prefix kolom

In [10]:
df.add_prefix("kolom_")

   kolom_A  kolom_B  kolom_C  kolom_D  kolom_E
0        2        9        1        1        7
1        2        8        9        7        2
2        5        3        6        9        6
3        1        9        6        1        9
4        8        6        5        7        2

## Menyertakan suffix kolom

In [13]:
df.add_suffix("_field")

   A_field  B_field  C_field  D_field  E_field
0        2        9        1        1        7
1        2        8        9        7        2
2        5        3        6        9        6
3        1        9        6        1        9
4        8        6        5        7        2