## 2. Pemilihan baris (rows selection) pada `DataFrame`

## Import modules

In [1]:
import pandas as pd
import numpy as np

## Persiapan `DataFrame`

In [3]:
n_rows = 10
n_cols = 5
cols = list("ABCDE")

df = pd.DataFrame(np.random.randint(1, 5, size=(n_rows, n_cols)), columns=cols)
df

   A  B  C  D  E
0  4  4  1  2  4
1  3  4  2  2  2
2  1  4  1  2  2
3  3  1  4  1  1
4  2  4  1  2  3
5  4  1  3  4  3
6  1  2  3  2  1
7  3  4  1  2  1
8  4  3  1  2  3
9  3  1  4  1  1

## Selection dengan operator logika `|`

In [6]:
df[(df["A"] == 1) | (df["A"] == 3)]

   A  B  C  D  E
1  3  4  2  2  2
2  1  4  1  2  2
3  3  1  4  1  1
6  1  2  3  2  1
7  3  4  1  2  1
9  3  1  4  1  1

## Selection dengan method `.isin()`

In [9]:
df[df["A"].isin([1, 3])]

   A  B  C  D  E
1  3  4  2  2  2
2  1  4  1  2  2
3  3  1  4  1  1
6  1  2  3  2  1
7  3  4  1  2  1
9  3  1  4  1  1

## Selection dengan operator `~`

In [12]:
df[~df["A"].isin([1, 3])]

   A  B  C  D  E
0  4  4  1  2  4
4  2  4  1  2  3
5  4  1  3  4  3
8  4  3  1  2  3